version: '3.2'
services:
  config:
    container_name: config
    image: config:1.0
    ports:
      - '8888:8888'
    restart: always
    volumes:
      - d:/spring-cloud/invako_msa/config:/usr/app/config # volume bind
    environment:
      SPRING_PROFILES_ACTIVE: native
      ENCRYPT_KEY: token_secret
      logstash_hostname: logstash:5001
      SEARCH_LOCATION: file:///usr/app/config
      RABBITMQ_HOSTNAME: rabbitmq
      ZIPKIN_HOSTNAME: zipkin
      TZ: Asia/Seoul
    healthcheck:
      test: curl -f http://localhost:8888/actuator/health || exit 1
      interval: 10s
      timeout: 1s
      retries: 10
      start_period: 30s

  discovery:
    container_name: discovery
    image: discovery:1.0
    ports:
      - '8761:8761'
    restart: always
    environment:
      SPRING_PROFILES_ACTIVE: default
      EUREKA_INSTANCE_HOSTNAME: discovery
      TZ: Asia/Seoul

  apigateway:
    container_name: apigateway
    image: apigateway:1.0
    ports:
      - '8000:8000'
    restart: always
    volumes:
      - d:/spring-cloud/invako_msa/msa-attach-volume:/usr/app/msa-attach-volume
    environment:
      SPRING_CLOUD_CONFIG_URI: http://config:8888
      SPRING_PROFILES_ACTIVE: default
      EUREKA_INSTANCE_HOSTNAME: discovery
      RABBITMQ_HOSTNAME: rabbitmq
      ZIPKIN_HOSTNAME: zipkin
      TOKEN_SECRET: egovframe
      APP_HOME: /usr/app
      TZ: Asia/Seoul
    depends_on:
      config:
        condition: service_healthy

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:management
    ports:
      - '5672:5672'
      - '15672:15672'
    restart: always
    environment:
      TZ: Asia/Seoul

  zipkin:
    container_name: zipkin
    image: openzipkin/zipkin
    ports:
      - '9411:9411'
    restart: always
    environment:
      TZ: Asia/Seoul

  userservice:
    container_name: userservice
    image: user-service:1.0
    restart: always
    volumes:
      - d:/spring-cloud/invako_msa/msa-attach-volume:/usr/app/msa-attach-volume
    environment:
      SPRING_CLOUD_CONFIG_URI: http://config:8888
      SPRING_PROFILES_ACTIVE: default
      MESSAGES_DIRECTORY: /usr/app/msa-attach-volume/messages
      APP_HOME: /usr/app
      logstash_hostname: logstash:5001
      EUREKA_INSTANCE_HOSTNAME: discovery
      MYSQL_HOSTNAME: mysql
      RABBITMQ_HOSTNAME: rabbitmq
      ZIPKIN_HOSTNAME: zipkin
      TOKEN_SECRET: egovframe
      TZ: Asia/Seoul
    depends_on:
      config:
        condition: service_healthy

  boardservice:
    container_name: boardservice
    image: board-service:1.0
    restart: always
    volumes:
      - d:/spring-cloud/invako_msa/msa-attach-volume:/usr/app/msa-attach-volume
    environment:
      SPRING_CLOUD_CONFIG_URI: http://config:8888
      SPRING_PROFILES_ACTIVE: default
      MESSAGES_DIRECTORY: /usr/app/msa-attach-volume/messages
      APP_HOME: /usr/app
      logstash_hostname: logstash:5001
      EUREKA_INSTANCE_HOSTNAME: discovery
      MYSQL_HOSTNAME: mysql
      RABBITMQ_HOSTNAME: rabbitmq
      ZIPKIN_HOSTNAME: zipkin
      TOKEN_SECRET: egovframe
      TZ: Asia/Seoul
    depends_on:
      config:
        condition: service_healthy

  portalservice:
    container_name: portalservice
    image: portal-service:1.0
    restart: always
    volumes:
      - d:/spring-cloud/invako_msa/msa-attach-volume:/usr/app/msa-attach-volume
    environment:
      SPRING_CLOUD_CONFIG_URI: http://config:8888
      SPRING_PROFILES_ACTIVE: default
      MESSAGES_DIRECTORY: /usr/app/msa-attach-volume/messages
      APP_HOME: /usr/app
      logstash_hostname: logstash:5001
      EUREKA_INSTANCE_HOSTNAME: discovery
      MYSQL_HOSTNAME: mysql
      RABBITMQ_HOSTNAME: rabbitmq
      ZIPKIN_HOSTNAME: zipkin
      TOKEN_SECRET: egovframe
      TZ: Asia/Seoul
    depends_on:
      config:
        condition: service_healthy

  reserve-check-service:
    container_name: reserve-check-service
    image: reserve-check-service:1.0
    restart: always
    volumes:
      - d:/spring-cloud/invako_msa/msa-attach-volume:/usr/app/msa-attach-volume
    environment:
      SPRING_CLOUD_CONFIG_URI: http://config:8888
      SPRING_PROFILES_ACTIVE: default
      MESSAGES_DIRECTORY: /usr/app/msa-attach-volume/messages
      APP_HOME: /usr/app
      logstash_hostname: logstash:5001
      EUREKA_INSTANCE_HOSTNAME: discovery
      MYSQL_HOSTNAME: mysql
      RABBITMQ_HOSTNAME: rabbitmq
      ZIPKIN_HOSTNAME: zipkin
      TOKEN_SECRET: egovframe
      TZ: Asia/Seoul
    depends_on:
      config:
        condition: service_healthy

  reserve-item-service:
    container_name: reserve-item-service
    image: reserve-item-service:1.0
    restart: always
    volumes:
      - d:/spring-cloud/invako_msa/msa-attach-volume:/usr/app/msa-attach-volume
    environment:
      SPRING_CLOUD_CONFIG_URI: http://config:8888
      SPRING_PROFILES_ACTIVE: default
      MESSAGES_DIRECTORY: /usr/app/msa-attach-volume/messages
      APP_HOME: /usr/app
      logstash_hostname: logstash:5001
      EUREKA_INSTANCE_HOSTNAME: discovery
      MYSQL_HOSTNAME: mysql
      RABBITMQ_HOSTNAME: rabbitmq
      ZIPKIN_HOSTNAME: zipkin
      TOKEN_SECRET: egovframe
      TZ: Asia/Seoul
    depends_on:
      config:
        condition: service_healthy

  reserve-request-service:
    container_name: reserve-request-service
    image: reserve-request-service:1.0
    restart: always
    volumes:
      - d:/spring-cloud/invako_msa/msa-attach-volume:/usr/app/msa-attach-volume
    environment:
      SPRING_CLOUD_CONFIG_URI: http://config:8888
      SPRING_PROFILES_ACTIVE: default
      MESSAGES_DIRECTORY: /usr/app/msa-attach-volume/messages
      APP_HOME: /usr/app
      logstash_hostname: logstash:5001
      EUREKA_INSTANCE_HOSTNAME: discovery
      MYSQL_HOSTNAME: mysql
      RABBITMQ_HOSTNAME: rabbitmq
      ZIPKIN_HOSTNAME: zipkin
      TOKEN_SECRET: egovframe
      TZ: Asia/Seoul
    depends_on:
      config:
        condition: service_healthy

networks:
  default:
    external:
      name: egov-network
