version: '3.2'
services:
  userservice:
    container_name: userservice
    image: user-service:1.0
    restart: always
    volumes:
      - d:/spring-cloud/invako_msa/msa-attach-volume:/usr/app/msa-attach-volume
    environment:
      SPRING_CLOUD_CONFIG_URI: http://config:8888
      SPRING_PROFILES_ACTIVE: default
      MESSAGES_DIRECTORY: /usr/app/msa-attach-volume/messages
      APP_HOME: /usr/app
      logstash_hostname: logstash:5001
      EUREKA_INSTANCE_HOSTNAME: discovery
      MYSQL_HOSTNAME: mysql
      RABBITMQ_HOSTNAME: rabbitmq
      ZIPKIN_HOSTNAME: zipkin
      TOKEN_SECRET: egovframe
      TZ: Asia/Seoul

  boardservice:
    container_name: boardservice
    image: board-service:1.0
    restart: always
    volumes:
      - d:/spring-cloud/invako_msa/msa-attach-volume:/usr/app/msa-attach-volume
    environment:
      SPRING_CLOUD_CONFIG_URI: http://config:8888
      SPRING_PROFILES_ACTIVE: default
      MESSAGES_DIRECTORY: /usr/app/msa-attach-volume/messages
      APP_HOME: /usr/app
      logstash_hostname: logstash:5001
      EUREKA_INSTANCE_HOSTNAME: discovery
      MYSQL_HOSTNAME: mysql
      RABBITMQ_HOSTNAME: rabbitmq
      ZIPKIN_HOSTNAME: zipkin
      TOKEN_SECRET: egovframe
      TZ: Asia/Seoul

  portalservice:
    container_name: portalservice
    image: portal-service:1.0
    restart: always
    volumes:
      - d:/spring-cloud/invako_msa/msa-attach-volume:/usr/app/msa-attach-volume
    environment:
      SPRING_CLOUD_CONFIG_URI: http://config:8888
      SPRING_PROFILES_ACTIVE: default
      MESSAGES_DIRECTORY: /usr/app/msa-attach-volume/messages
      APP_HOME: /usr/app
      logstash_hostname: logstash:5001
      EUREKA_INSTANCE_HOSTNAME: discovery
      MYSQL_HOSTNAME: mysql
      RABBITMQ_HOSTNAME: rabbitmq
      ZIPKIN_HOSTNAME: zipkin
      TOKEN_SECRET: egovframe
      TZ: Asia/Seoul

  reserve-check-service:
    container_name: reserve-check-service
    image: reserve-check-service:1.0
    restart: always
    volumes:
      - d:/spring-cloud/invako_msa/msa-attach-volume:/usr/app/msa-attach-volume
    environment:
      SPRING_CLOUD_CONFIG_URI: http://config:8888
      SPRING_PROFILES_ACTIVE: default
      MESSAGES_DIRECTORY: /usr/app/msa-attach-volume/messages
      APP_HOME: /usr/app
      logstash_hostname: logstash:5001
      EUREKA_INSTANCE_HOSTNAME: discovery
      MYSQL_HOSTNAME: mysql
      RABBITMQ_HOSTNAME: rabbitmq
      ZIPKIN_HOSTNAME: zipkin
      TOKEN_SECRET: egovframe
      TZ: Asia/Seoul

  reserve-item-service:
    container_name: reserve-item-service
    image: reserve-item-service:1.0
    restart: always
    volumes:
      - d:/spring-cloud/invako_msa/msa-attach-volume:/usr/app/msa-attach-volume
    environment:
      SPRING_CLOUD_CONFIG_URI: http://config:8888
      SPRING_PROFILES_ACTIVE: default
      MESSAGES_DIRECTORY: /usr/app/msa-attach-volume/messages
      APP_HOME: /usr/app
      logstash_hostname: logstash:5001
      EUREKA_INSTANCE_HOSTNAME: discovery
      MYSQL_HOSTNAME: mysql
      RABBITMQ_HOSTNAME: rabbitmq
      ZIPKIN_HOSTNAME: zipkin
      TOKEN_SECRET: egovframe
      TZ: Asia/Seoul

  reserve-request-service:
    container_name: reserve-request-service
    image: reserve-request-service:1.0
    restart: always
    volumes:
      - d:/spring-cloud/invako_msa/msa-attach-volume:/usr/app/msa-attach-volume
    environment:
      SPRING_CLOUD_CONFIG_URI: http://config:8888
      SPRING_PROFILES_ACTIVE: default
      MESSAGES_DIRECTORY: /usr/app/msa-attach-volume/messages
      APP_HOME: /usr/app
      logstash_hostname: logstash:5001
      EUREKA_INSTANCE_HOSTNAME: discovery
      MYSQL_HOSTNAME: mysql
      RABBITMQ_HOSTNAME: rabbitmq
      ZIPKIN_HOSTNAME: zipkin
      TOKEN_SECRET: egovframe
      TZ: Asia/Seoul

networks:
  default:
    name: egov-network
    external: true
