version: '3.2'
services:
  front-admin-service:
    container_name: front-admin-service
    image: frontend-admin:1.0
    ports:
      - '3000:3000'
    restart: always
    environment:
      TZ: Asia/Seoul

  front-portal-service:
    container_name: front-portal-service
    image: frontend-portal:1.0
    ports:
      - '3001:3001'
    restart: always
    environment:
      TZ: Asia/Seoul

networks:
  default:
    external:
      name: egov-network
